[general]
import = [ "~/.config/alacritty/theme.toml" ]

[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
startup_mode = "Maximized"
option_as_alt = "Both" # macOS only

[font]
size = 15
normal = { family = "JetBrainsMonoNL Nerd Font Mono", style = "Light" }

[cursor]
style = { blinking = "On" }
blink_interval = 500
blink_timeout = 0
